package com.vvchn.avitotesttask.common

import java.util.concurrent.TimeoutException

enum class Countries(val country: String) {
    AUSTRALIA("Австралия"),
    AUSTRIA("Австрия"),
    AZERBAIJAN("Азербайджан"),
    ALBANIA("Албания"),
    ALGERIA("Алжир"),
    ANGOLA("Ангола"),
    ANDORA("Андорра"),
    ANTIGUA_AND_BARBUDA("Антигуа и Барбуда"),
    ARGENTINA("Аргентина"),
    ARMENIA("Армения"),
    AFGHANISTAN("Афганистан"),
    BANGLADESH("Бангладеш"),
    BARBADOS("Барбадос"),
    BAHRAIN("Бахрейн"),
    BELIZE("Белиз"),
    BELARUS("Белоруссия"),
    BELGIUM("Бельгия"),
    BENIN("Бенин"),
    BULGARIA("Болгария"),
    BOLIVIA("Боливия"),
    BOSNIA_AND_HERZEGOVINA("Босния и Герцеговина"),
    BOTSWAN("Ботсвана"),
    BRAZIL("Бразилия"),
    BRUNEI_DARUSSALAM("Бруней"),
    BURKINA_FASO("Буркина-Фасо"),
    BURUNDI("Бурунди"),
    BHUTAN("Бутан"),
    VANUATU("Вануату"),
    VATICAN_CITY("Ватикан"),
    UNITED_KINGDOM("Великобритания"),
    HUNGARY("Венгрия"),
    VENEZUELA("Венесуэла"),
    VIETNAM("Вьетнам"),
    GABON("Габон"),
    HAITI("Гаити"),
    GUYANA("Гайана"),
    GAMBIA("Гамбия"),
    GHANA("Гана"),
    GUATEMALA("Гватемала"),
    GUINEA("Гвинея"),
    GUINEA_BISSAU("Гвинея-Бисау"),
    GERMANY("Германия"),
    HONDURAS("Гондурас"),
    GRENADA("Гренада"),
    GREECE("Греция"),
    GEORGIA("Грузия"),
    DENMARK("Дания"),
    DJIBOUTI("Джибути"),
    EGYPT("Египет"),
    ZAMBIA("Замбия"),
    ZIMBABWE("Зимбабве"),
    ISRAEL("Израиль"),
    INDIA("Индия"),
    INDONESIA("Индонезия"),
    JORDAN("Иордания"),
    IRAQ("Ирак"),
    IRAN("Иран"),
    IRELAND("Ирландия"),
    ICELAND("Исландия"),
    SPAIN("Испания"),
    ITALY("Италия"),
    YEMEN("Йемен"),
    CAPE_VERDE("Кабо-Верде"),
    KAZAKHSTAN("Казахстан"),
    CAMBODIA("Камбоджа"),
    CAMEROON("Камерун"),
    CANADA("Канада"),
    QATAR("Катар"),
    KENYA("Кения"),
    CYPRUS("Кипр"),
    KYRGYZSTAN("Киргизия"),
    KIRIBATI("Кирибати"),
    СHINA("Китай"),
    COLUMBIA("Колумбия"),
    CONGO("Конго"),
    SOUTH_KOREA("Корея"),
    COSTA_RICA("Коста-Рика"),
    CUBA("Куба"),
    KUWAIT("Кувейт"),
    LAOS("Лаос"),
    LATVIA("Латвия"),
    LESOTHO("Лесото"),
    LIBERIA("Либерия"),
    LEBANON("Ливан"),
    LIBYA("Ливия"),
    LITHUANIA("Литва"),
    LIECHTENSTEIN("Лихтенштейн"),
    LUXEMBOURG("Люксембург"),
    MAURITIUS("Маврикий"),
    MAURITANIA("Мавритания"),
    MADAGASCAR("Мадагаскар"),
    MALAWI("Малави"),
    MALAYSIA("Малайзия"),
    MALI("Мали"),
    MALTA("Мальта"),
    MOROCCO("Марокко"),
    MEXICO("Мексика"),
    MOZAMBIQUE("Мозамбик"),
    MOLDOVA("Молдавия"),
    MONACO("Монако"),
    MONGOLIA("Монголия"),
    MYANMAR("Мьянма"),
    NAMIBIA("Намибия"),
    NEPAL("Непал"),
    NIGER("Нигер"),
    NIGERIA("Нигерия"),
    NETHERLANDS("Нидерланды"),
    NICARAGUA("Никарагуа"),
    NEW_ZELAND("Новая Зеландия"),
    NORWAY("Норвегия"),
    UNITED_ARAB_EMIRATES("ОАЭ"),
    OMAN("Оман"),
    PAKISTAN("Пакистан"),
    PALAU("Палау"),
    PANAMA("Панама"),
    PAPUA_NEW_GUINEA("Папуа - Новая Гвинея"),
    PALESTINE("Палестина"),
    PARAGUAY("Парагвай"),
    PERU("Перу"),
    POLAND("Польша"),
    PORTUGAL("Португалия"),
    RUSSIA("Россия"),
    RWANDA("Руанда"),
    ROMANIA("Румыния"),
    EL_SALVADOR("Сальвадор"),
    SAMOA("Самоа"),
    SAN_MARINO("Сан-Марино"),
    SAUDI_ARABIA("Саудовская Аравия"),
    NORTH_KOREA("Северная Корея"),
    NORTH_MACEDONIA("Северная Македония"),
    SENEGAL("Сенегал"),
    SAINT_KITTS_AND_NEVIS("Сент-Китс и Невис"),
    SERBIA("Сербия"),
    SINGAPORE("Сингапур"),
    SYRIA("Сирия"),
    SLOVAKIA("Словакия"),
    SLOVENIA("Словения"),
    SOMALIA("Сомали"),
    USSR("СССР"),
    SUDAN("Судан"),
    SURINAME("Суринам"),
    USA("США"),
    SIERRA_LEONE("Сьерра-Леоне"),
    TAJIKISTAN("Таджикистан"),
    THAILAND("Таиланд"),
    TANZANIA("Танзания"),
    TOGO("Того"),
    TRINIDAD_AND_TOBAGO("Тринидад и Тобаго"),
    TUVALU("Тувалу"),
    TUNISIA("Тунис"),
    TURKMENISTAN("Туркмения"),
    TURKEY("Турция"),
    UGANDA("Уганда"),
    UZBEKISTAN("Узбекистан"),
    UKRAINE("Украина"),
    URUGUAY("Уругвай"),
    FEDERATED_STATES_OF_MICRONESIA("Федеративные Штаты Микронезии"),
    FIJI("Фиджи"),
    PHILIPPINES("Филиппины"),
    FINLAND("Финляндия"),
    FRANCE("Франция"),
    CROATIA("Хорватия"),
    CENTRAL_AFRICAN_REPUBLIC("ЦАР"),
    CHAD("Чад"),
    MONTENEGRO("Черногория"),
    CZECH_REPUBLIC("Чехия"),
    CHILE("Чили"),
    SWITZERLAND("Швейцария"),
    SWEDEN("Швеция"),
    SRI_LANKA("Шри-Ланка"),
    ECUADOR("Эквадор"),
    GUINEA_ECUATORIAL("Экваториальная Гвинея"),
    ERITREA("Эритрея"),
    ESTONIA("Эстония"),
    ETHIOPIA("Эфиопия"),
    SOUTH_AFRICA("ЮАР"),
    JAMAICA("Ямайка"),
    JAPAN("Япония"),
}

enum class Genres {

}